[project]
name = "crimax-sports-backend"
version = "0.1.0"
description = "Crimax Sports API"
requires-python = "==3.12.*"
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.14.2",
    "asyncpg==0.30.0",
    "bcrypt==4.2.0",
    "bleach==6.2.0",
    "certifi==2026.6.17",
    "cffi==2.1.0",
    "click==8.4.2",
    "cloudinary==1.45.0",
    "cryptography==43.0.3",
    "dnspython==2.8.0",
    "ecdsa==0.19.2",
    "email_validator==2.2.0",
    "fastapi[standard]==0.115.0",
    "h11==0.16.0",
    "httpx==0.28.1",
    "httptools==0.8.0",
    "idna==3.18",
    "pyasn1==0.6.4",
    "pycparser==3.0",
    "pydantic==2.9.2",
    "pydantic-settings==2.5.2",
    "pydantic_core==2.23.4",
    "python-dotenv==1.0.1",
    "python-jose==3.3.0",
    "python-multipart==0.0.12",
    "PyYAML==6.0.3",
    "rsa==4.9.1",
    "six==1.17.0",
    "starlette==0.38.6",
    "typing_extensions==4.16.0",
    "urllib3==2.7.0",
    "uvicorn==0.30.6",
    "uvloop==0.22.1",
    "watchfiles==1.2.0",
    "websockets==16.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["sql*", "tests*", "scripts*"]

[tool.fastapi]
entrypoint = "app.main:app"
